[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 3001  # ✅ Correctly set Vite's port
  command = "npm run dev"
  publish = "dist"
  autoLaunch = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"  # ✅ Keep only one instance

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co;
      script-src 'self' 'unsafe-inline' https://*.supabase.co https://o4508848989929472.ingest.us.sentry.io;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.unsplash.com https://*.supabase.co https://storage.googleapis.com https://*.netlify.app https://o4508848989929472.ingest.us.sentry.io;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://o4508848989929472.ingest.us.sentry.io;
      frame-ancestors 'self';
    """
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"