import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";

import { X, Download, ArrowLeft, ArrowRight } from 'lucide-react';
import { Button } from '../ui/Button';
export function FormPreview({ formId, onClose, onDownload }) {
    const [currentPage, setCurrentPage] = React.useState(1);
    const totalPages = 4; // Example value
    return (_jsx("div", { className: "fixed inset-0 z-50 overflow-hidden bg-gray-500 bg-opacity-75", children: _jsx("div", { className: "fixed inset-0 overflow-hidden", children: _jsx("div", { className: "absolute inset-0 overflow-hidden", children: _jsx("div", { className: "fixed inset-y-0 right-0 flex max-w-full pl-10", children: _jsx("div", { className: "w-screen max-w-4xl", children: _jsxs("div", { className: "flex h-full flex-col bg-white shadow-xl", children: [_jsxs("div", { className: "flex items-center justify-between px-4 py-6 sm:px-6", children: [_jsx("h2", { className: "text-lg font-medium text-gray-900", children: "Form Preview" }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "text-sm text-gray-500", children: ["Page ", currentPage, " of ", totalPages] }), _jsx(Button, { variant: "outline", size: "sm", icon: Download, onClick: () => onDownload(formId), children: "Download" }), _jsx(Button, { variant: "ghost", size: "sm", icon: X, onClick: onClose })] })] }), _jsx("div", { className: "relative flex-1 px-4 sm:px-6", children: _jsx("div", { className: "h-full bg-gray-100 rounded-lg" }) }), _jsxs("div", { className: "flex items-center justify-between px-4 py-4 sm:px-6 border-t border-gray-200", children: [_jsx(Button, { variant: "outline", size: "sm", icon: ArrowLeft, disabled: currentPage === 1, onClick: () => setCurrentPage(prev => prev - 1), children: "Previous" }), _jsx(Button, { variant: "outline", size: "sm", icon: ArrowRight, iconPosition: "right", disabled: currentPage === totalPages, onClick: () => setCurrentPage(prev => prev + 1), children: "Next" })] })] }) }) }) }) }) }));
}
